/**
 * Studio-space-rental shapes — the Airbnb-for-production-studios surface.
 *
 * Space owners (creators on the platform) list bookable physical studios with
 * photos, hourly + daily rates, capacity, and equipment. Creators browse and
 * book by date range. Money in halalas (1 SAR = 100 halalas) per the rest of
 * the codebase. Mirrors the `lib/store` module — the closest existing pattern
 * to what we're building here.
 */

import type { City } from '@/lib/creators/mock-data';

export type SpaceCity = City;

export type SpaceStatus = 'DRAFT' | 'ACTIVE' | 'PAUSED';

export type BookingStatus = 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'COMPLETED';

export type BookingDurationKind = 'HOURLY' | 'DAILY';

export interface Space {
  id: string;
  /** mock-auth user id of the owner. */
  ownerId: string;
  name: string;
  description: string;
  address: string;
  city: SpaceCity;
  /** Maximum people the space comfortably holds. */
  capacity: number;
  /** Per-hour rate in halalas. */
  hourlyHalalas: number;
  /** Per-day rate in halalas. */
  dailyHalalas: number;
  /** Free-text tags surfaced as chips on the detail page. */
  equipmentIncluded: string[];
  /** 1–10 photo URLs. First is the hero. */
  photos: string[];
  status: SpaceStatus;
  createdAt: string;
}

export interface SpaceBooking {
  id: string;
  spaceId: string;
  /** mock-auth user id of the renter. */
  renterId: string;
  /** ISO datetime — the start of the booked window. */
  startISO: string;
  /** ISO datetime — the (exclusive) end of the booked window. */
  endISO: string;
  durationKind: BookingDurationKind;
  /** Total cost in halalas at booking time. */
  totalHalalas: number;
  status: BookingStatus;
  createdAt: string;
}

/* -------------------------------- seed --------------------------------- */

const pic = (seed: string, w: number, h: number): string =>
  `https://picsum.photos/seed/space-${seed}/${w}/${h}`;

// The seed user id for `noor@hikaya.sa` is generated by randomUUID() at boot,
// so we can't hardcode it here. The mock-store keeps these placeholder
// owner ids and the seed runs as-is — the demo owner is rebound to whoever
// is signed in via the `/me/spaces` flow.
export const SEED_OWNER_PLACEHOLDER = 'u_noor_demo';

const now = new Date().toISOString();
const SAR = 100;

export const SEED_SPACES: Space[] = [
  {
    id: 'sp_noor_cyc_riyadh',
    ownerId: SEED_OWNER_PLACEHOLDER,
    name: 'Cyc Wall Studio — Olaya',
    description:
      'A 90sqm shooting bay with a seamless white cyclorama, 4m ceilings, and three Profoto B10X heads on stands. Drive-in access through a roller door for product or talent shoots.',
    address: 'King Fahd Road, Olaya',
    city: 'RIYADH',
    capacity: 12,
    hourlyHalalas: 250 * SAR,
    dailyHalalas: 1800 * SAR,
    equipmentIncluded: ['Cyclorama', 'Profoto B10X x3', 'Backdrops', 'C-stands'],
    photos: [
      pic('cyc-1', 1600, 1067),
      pic('cyc-2', 1600, 1067),
      pic('cyc-3', 1600, 1067),
    ],
    status: 'ACTIVE',
    createdAt: now,
  },
  {
    id: 'sp_noor_daylight_jeddah',
    ownerId: SEED_OWNER_PLACEHOLDER,
    name: 'North-Facing Daylight Loft — Al Hamra',
    description:
      'Quiet 6th-floor loft with north-facing floor-to-ceiling windows. Soft daylight from 9am to 4pm year-round. Hardwood floors, neutral walls, and a small kitchenette for catering.',
    address: 'Al Hamra District',
    city: 'JEDDAH',
    capacity: 8,
    hourlyHalalas: 180 * SAR,
    dailyHalalas: 1200 * SAR,
    equipmentIncluded: ['Diffusion frames', 'Reflectors', 'Wardrobe rack', 'Kitchenette'],
    photos: [
      pic('daylight-1', 1600, 1067),
      pic('daylight-2', 1600, 1067),
      pic('daylight-3', 1600, 1067),
    ],
    status: 'ACTIVE',
    createdAt: now,
  },
  {
    id: 'sp_noor_podcast_riyadh',
    ownerId: SEED_OWNER_PLACEHOLDER,
    name: 'Three-Camera Podcast Studio — Diplomatic Quarter',
    description:
      'Pre-lit four-seat podcast set with three Sony FX3 cameras, Shure SM7B mics, and a Rodecaster Pro II. Plug your laptop into the multitrack feed and walk out with audio + ISO recordings.',
    address: 'Diplomatic Quarter',
    city: 'RIYADH',
    capacity: 6,
    hourlyHalalas: 350 * SAR,
    dailyHalalas: 2400 * SAR,
    equipmentIncluded: ['Sony FX3 x3', 'Shure SM7B x4', 'Rodecaster Pro II', 'Engineer included'],
    photos: [
      pic('podcast-1', 1600, 1067),
      pic('podcast-2', 1600, 1067),
    ],
    status: 'ACTIVE',
    createdAt: now,
  },
  {
    id: 'sp_noor_rooftop_khobar',
    ownerId: SEED_OWNER_PLACEHOLDER,
    name: 'Corniche Rooftop — Golden Hour',
    description:
      'Open-air rooftop on the Khobar Corniche with unobstructed Gulf views. Ideal for fashion editorials, music videos, and BTS golden-hour content. Power and shade available.',
    address: 'Corniche Road',
    city: 'KHOBAR',
    capacity: 20,
    hourlyHalalas: 220 * SAR,
    dailyHalalas: 1500 * SAR,
    equipmentIncluded: ['Power drops', 'Shade canopy', 'Loading lift'],
    photos: [
      pic('rooftop-1', 1600, 1067),
      pic('rooftop-2', 1600, 1067),
    ],
    status: 'ACTIVE',
    createdAt: now,
  },
  {
    id: 'sp_noor_blackbox_jeddah',
    ownerId: SEED_OWNER_PLACEHOLDER,
    name: 'Blackbox Stage — Andalus',
    description:
      'Light-tight 120sqm blackbox with a 6x6m green-screen drop, dimmable Aputure 1200d, and a small grip kit. Sound-deadened walls, suitable for drama and commercial work.',
    address: 'Andalus District',
    city: 'JEDDAH',
    capacity: 15,
    hourlyHalalas: 280 * SAR,
    dailyHalalas: 1950 * SAR,
    equipmentIncluded: ['Green screen', 'Aputure 1200d', 'C-stands', 'Sound dampening'],
    photos: [
      pic('blackbox-1', 1600, 1067),
      pic('blackbox-2', 1600, 1067),
      pic('blackbox-3', 1600, 1067),
    ],
    status: 'ACTIVE',
    createdAt: now,
  },
  {
    id: 'sp_noor_lounge_riyadh',
    ownerId: SEED_OWNER_PLACEHOLDER,
    name: 'Lounge Set — Diriyah',
    description:
      'Furnished majlis-style lounge set with warm practical lighting. Built for lifestyle interviews and content shoots — three camera positions pre-marked, props library on site.',
    address: 'Diriyah',
    city: 'RIYADH',
    capacity: 10,
    hourlyHalalas: 200 * SAR,
    dailyHalalas: 1400 * SAR,
    equipmentIncluded: ['Practical lights', 'Props library', 'Wardrobe room'],
    photos: [
      pic('lounge-1', 1600, 1067),
      pic('lounge-2', 1600, 1067),
    ],
    status: 'ACTIVE',
    createdAt: now,
  },
];

// Two pre-existing bookings, just for the public detail page to have realistic
// "next booked dates" copy. The renter id is the placeholder client; the live
// flow will rebind on first sign-in.
export const SEED_RENTER_PLACEHOLDER = 'u_client_demo';

function isoDaysFromNow(days: number, hour = 9): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const SEED_BOOKINGS: SpaceBooking[] = [
  {
    id: 'sb_seed_1',
    spaceId: 'sp_noor_cyc_riyadh',
    renterId: SEED_RENTER_PLACEHOLDER,
    startISO: isoDaysFromNow(5, 9),
    endISO: isoDaysFromNow(5, 18),
    durationKind: 'DAILY',
    totalHalalas: 1800 * SAR,
    status: 'CONFIRMED',
    createdAt: now,
  },
  {
    id: 'sb_seed_2',
    spaceId: 'sp_noor_podcast_riyadh',
    renterId: SEED_RENTER_PLACEHOLDER,
    startISO: isoDaysFromNow(12, 14),
    endISO: isoDaysFromNow(12, 18),
    durationKind: 'HOURLY',
    totalHalalas: 4 * 350 * SAR,
    status: 'PENDING',
    createdAt: now,
  },
];
