import PDFDocument from 'pdfkit';

import type { Quote } from './mock-data';

const sar = (halalas: number): string =>
  new Intl.NumberFormat('en-SA', {
    style: 'currency',
    currency: 'SAR',
    minimumFractionDigits: 2,
  }).format(halalas / 100);

/**
 * Render a Quote/Invoice as a ZATCA-friendly PDF.
 *
 * Includes the sequence number (Quote.number), VAT line at 15%, subtotal,
 * discount, and total. Does NOT submit to ZATCA's e-invoicing endpoint —
 * that requires the production certificate flow which is out of scope.
 */
export async function renderQuotePdf(quote: Quote): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ---- Header
      doc
        .fontSize(24)
        .fillColor('#18012b')
        .text('Hikaya', { align: 'left' });
      doc
        .fontSize(10)
        .fillColor('#5d4f6a')
        .text('Tax Invoice / Quote', { align: 'left' });
      doc.moveDown(1);

      // ---- Meta block (right-aligned)
      const metaTop = doc.y;
      doc
        .fontSize(10)
        .fillColor('#18012b')
        .text(`Quote #: ${quote.number}`, 350, metaTop)
        .text(
          `Date:    ${new Date(quote.createdAt).toLocaleDateString('en-SA')}`,
          350,
          metaTop + 14,
        );
      if (quote.expiresAt) {
        doc.text(
          `Expires: ${new Date(quote.expiresAt).toLocaleDateString('en-SA')}`,
          350,
          metaTop + 28,
        );
      }

      // ---- Bill-to
      doc
        .fontSize(11)
        .fillColor('#5d4f6a')
        .text('Bill to', 50, metaTop)
        .fontSize(12)
        .fillColor('#18012b')
        .text(quote.clientName, 50, metaTop + 14);
      if (quote.clientEmail) {
        doc.fontSize(10).fillColor('#5d4f6a').text(quote.clientEmail, 50, metaTop + 30);
      }

      doc.moveDown(4);

      // ---- Line items table
      const tableTop = doc.y + 10;
      const colDesc = 50;
      const colQty = 320;
      const colUnit = 380;
      const colTotal = 470;

      doc
        .fontSize(10)
        .fillColor('#5d4f6a')
        .text('Description', colDesc, tableTop)
        .text('Qty', colQty, tableTop, { width: 50, align: 'right' })
        .text('Unit', colUnit, tableTop, { width: 80, align: 'right' })
        .text('Total', colTotal, tableTop, { width: 80, align: 'right' });

      doc
        .moveTo(50, tableTop + 14)
        .lineTo(545, tableTop + 14)
        .strokeColor('#e0dcd2')
        .lineWidth(0.5)
        .stroke();

      let y = tableTop + 22;
      doc.fontSize(11).fillColor('#18012b');
      for (const li of quote.lineItems) {
        doc.text(li.descriptionEn, colDesc, y, { width: 260 });
        doc.text(String(li.quantity), colQty, y, { width: 50, align: 'right' });
        doc.text(sar(li.unitHalalas), colUnit, y, { width: 80, align: 'right' });
        doc.text(sar(li.totalHalalas), colTotal, y, { width: 80, align: 'right' });
        const blockHeight = doc.heightOfString(li.descriptionEn, { width: 260 });
        y += Math.max(20, blockHeight + 8);
      }

      // ---- Totals block
      doc
        .moveTo(320, y + 6)
        .lineTo(545, y + 6)
        .strokeColor('#e0dcd2')
        .stroke();

      let ty = y + 14;
      const rightLabel = (label: string, value: string, bold = false) => {
        doc.fontSize(bold ? 12 : 10).fillColor(bold ? '#18012b' : '#5d4f6a');
        doc.text(label, 320, ty, { width: 140, align: 'right' });
        doc.fillColor('#18012b').text(value, 470, ty, { width: 80, align: 'right' });
        ty += bold ? 22 : 16;
      };

      rightLabel('Subtotal', sar(quote.subtotalHalalas));
      if (quote.discountHalalas > 0) {
        rightLabel('Discount', `- ${sar(quote.discountHalalas)}`);
      }
      rightLabel('VAT (15%)', sar(quote.vatHalalas));
      ty += 4;
      rightLabel('Total due', sar(quote.totalHalalas), true);

      // ---- Notes
      if (quote.notes) {
        doc.moveDown(3);
        doc.fontSize(10).fillColor('#5d4f6a').text('Notes', 50);
        doc.moveDown(0.3);
        doc.fontSize(11).fillColor('#18012b').text(quote.notes, 50, doc.y, { width: 495 });
      }

      // ---- Footer
      const footerY = 780;
      doc
        .fontSize(8)
        .fillColor('#5d4f6a')
        .text(
          'Generated by Hikaya · hikaya.sa · This document includes a 15% VAT line as required by ZATCA.',
          50,
          footerY,
          { width: 495, align: 'center' },
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
